from __future__ import annotations

import datetime as dt
import hashlib
import json
from pathlib import Path

from .config import ProjectConfig, Repository
from .gitops import git_output

EXCLUDED_DIRS = {
    ".git", ".mypy_cache", ".pytest_cache", ".ruff_cache", ".venv", "venv", "__pycache__",
    "build", "dist", ".gradle", ".idea", ".vscode", "node_modules", "target", ".next", "coverage",
}
EXCLUDED_SUFFIXES = {".pyc", ".pyo", ".log", ".sqlite", ".db", ".DS_Store"}
INCLUDED_ROOT_FILES = {
    "Dockerfile", "Containerfile", "pyproject.toml", "package.json", "package-lock.json", "pnpm-lock.yaml",
    "yarn.lock", "go.mod", "go.sum", "pom.xml", "build.gradle", "settings.gradle", "README.md",
    "constraints.txt", "MANIFEST.in", "Makefile", "docker-entrypoint.sh", ".env.example", "pytest.ini",
}
DEFAULT_INCLUDE_ROOTS = {"src", "tests", "openapi", "docs", "app", "lib", "cmd", "internal", "pkg", "public"}


def iter_fingerprint_files(path: Path, include_roots: list[str] | None = None):
    roots = set(include_roots or []) or DEFAULT_INCLUDE_ROOTS
    for file in sorted(path.rglob("*")):
        if not file.is_file():
            continue
        rel = file.relative_to(path)
        if any(part in EXCLUDED_DIRS for part in rel.parts):
            continue
        if file.suffix in EXCLUDED_SUFFIXES:
            continue
        if rel.parts[0] in roots:
            yield file
            continue
        if len(rel.parts) == 1 and rel.name in INCLUDED_ROOT_FILES:
            yield file


def digest_path(path: Path, include_roots: list[str] | None = None) -> str:
    h = hashlib.sha256()
    for file in iter_fingerprint_files(path, include_roots):
        rel = file.relative_to(path).as_posix()
        h.update(rel.encode("utf-8")); h.update(b"\0")
        h.update(file.read_bytes()); h.update(b"\0")
    return h.hexdigest()


def env_prefix(name: str, project_prefix: str = "RFM") -> str:
    return project_prefix.upper().replace("-", "_") + "_" + name.upper().replace("-", "_")


def build_metadata(config: ProjectConfig, root: Path) -> dict:
    build_time = dt.datetime.now(dt.UTC).replace(microsecond=0).isoformat()
    services = []
    for repo in config.services():
        path = root / repo.path
        if not path.exists():
            continue
        full = digest_path(path, repo.include_roots)
        head = git_output(["rev-parse", "--short=12", "HEAD"], path) or "nogit"
        dirty = bool(git_output(["status", "--porcelain", "--untracked-files=all"], path))
        services.append({
            "name": repo.service_name,
            "repo": repo.repo,
            "path": repo.path,
            "host_port": repo.host_port,
            "git_head": head,
            "dirty": dirty,
            "build_sha": f"{head}-dirty" if dirty else head,
            "source_digest": full[:16],
            "source_digest_full": full,
        })
    return {"project": config.project.get("name"), "build_time": build_time, "services": services}


def write_metadata(config: ProjectConfig, root: Path, metadata: dict) -> Path:
    build_dir = root / str(config.project.get("build_dir", ".repo-fleet/build"))
    build_dir.mkdir(parents=True, exist_ok=True)
    (build_dir / "metadata.json").write_text(json.dumps(metadata, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    prefix = str(config.project.get("env_prefix", "RFM"))
    env_lines = ["# Generated by Repo Fleet Manager", "# Do not edit manually.", f"{prefix}_BUILD_TIME={metadata['build_time']}"]
    for service in metadata["services"]:
        p = env_prefix(service["name"], prefix)
        env_lines += [f"{p}_BUILD_SHA={service['build_sha']}", f"{p}_BUILD_SOURCE_DIGEST={service['source_digest']}"]
    (build_dir / "build.env").write_text("\n".join(env_lines) + "\n", encoding="utf-8")
    base_env = root / str(config.compose.get("env_file", "infra-compose/.env.example"))
    parts = []
    if base_env.exists():
        parts.append(base_env.read_text(encoding="utf-8").rstrip())
    parts.append("\n".join(env_lines))
    (build_dir / "compose.env").write_text("\n\n".join(parts).rstrip() + "\n", encoding="utf-8")
    return build_dir


def write_compose_override(config: ProjectConfig, root: Path, metadata: dict) -> Path:
    build_dir = root / str(config.project.get("build_dir", ".repo-fleet/build"))
    build_dir.mkdir(parents=True, exist_ok=True)
    prefix = str(config.project.get("env_prefix", "RFM"))
    lines = ["# Generated by Repo Fleet Manager", "# Do not edit manually.", "services:"]
    for service in metadata["services"]:
        p = env_prefix(service["name"], prefix)
        n = service["name"]
        lines += [
            f"  {n}:",
            "    build:",
            "      args:",
            f"        {prefix}_BUILD_SHA: ${{{p}_BUILD_SHA}}",
            f"        {prefix}_BUILD_SOURCE_DIGEST: ${{{p}_BUILD_SOURCE_DIGEST}}",
            f"        {prefix}_BUILD_TIME: ${{{prefix}_BUILD_TIME}}",
            "    environment:",
            f"      {prefix}_BUILD_SHA: ${{{p}_BUILD_SHA}}",
            f"      {prefix}_BUILD_SOURCE_DIGEST: ${{{p}_BUILD_SOURCE_DIGEST}}",
            f"      {prefix}_BUILD_TIME: ${{{prefix}_BUILD_TIME}}",
            "    labels:",
            f"      io.repo-fleet.service: {n}",
            f"      io.repo-fleet.repo: {service['repo']}",
            f"      io.repo-fleet.build-sha: ${{{p}_BUILD_SHA}}",
            f"      io.repo-fleet.source-digest: ${{{p}_BUILD_SOURCE_DIGEST}}",
            f"      io.repo-fleet.build-time: ${{{prefix}_BUILD_TIME}}",
        ]
    out = build_dir / "docker-compose.source-metadata.yml"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out
