#!/usr/bin/env python3
from __future__ import annotations
from pathlib import Path
import json, sys
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from goftaroo_service_catalog import env_prefix  # type: ignore
build_dir = ROOT / ".goftaroo-build"; metadata_file=build_dir/"metadata.json"
if not metadata_file.exists(): raise SystemExit("[ERROR] Missing .goftaroo-build/metadata.json. Run scripts/goftaroo-source-fingerprint.py --write first.")
metadata=json.loads(metadata_file.read_text(encoding="utf-8"))
lines=["# Generated by scripts/generate-compose-build-override.py","# Do not edit manually.","services:"]
for service in metadata["services"]:
    n=service["name"]; p=env_prefix(n)
    lines += [f"  {n}:","    build:","      args:",f"        GOFTAROO_BUILD_SHA: ${{{p}_BUILD_SHA}}",f"        GOFTAROO_BUILD_SOURCE_DIGEST: ${{{p}_BUILD_SOURCE_DIGEST}}","        GOFTAROO_BUILD_TIME: ${GOFTAROO_BUILD_TIME}","    environment:",f"      GOFTAROO_BUILD_SHA: ${{{p}_BUILD_SHA}}",f"      GOFTAROO_BUILD_SOURCE_DIGEST: ${{{p}_BUILD_SOURCE_DIGEST}}","      GOFTAROO_BUILD_TIME: ${GOFTAROO_BUILD_TIME}","    labels:",f"      ir.goftaroo.service: {n}",f"      ir.goftaroo.build-sha: ${{{p}_BUILD_SHA}}",f"      ir.goftaroo.source-digest: ${{{p}_BUILD_SOURCE_DIGEST}}","      ir.goftaroo.build-time: ${GOFTAROO_BUILD_TIME}"]
override=build_dir/"docker-compose.build-metadata.yml"; override.write_text("\n".join(lines)+"\n",encoding="utf-8"); print(f"[OK] Wrote {override}")
