#!/usr/bin/env python3
from __future__ import annotations
from pathlib import Path
import argparse, datetime as dt, hashlib, json, subprocess, sys
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from goftaroo_service_catalog import SERVICES, env_prefix  # type: ignore
EXCLUDED_DIRS = {".git", ".mypy_cache", ".pytest_cache", ".ruff_cache", ".venv", "venv", "__pycache__", "build", "dist", ".gradle", ".idea", ".vscode"}
EXCLUDED_SUFFIXES = {".pyc", ".pyo", ".log", ".sqlite", ".db"}
INCLUDED_ROOT_FILES = {"Dockerfile", "pyproject.toml", "README.md", "constraints.txt", "MANIFEST.in", "Makefile", "docker-entrypoint.sh", ".env.example", "pytest.ini"}
def run(cmd, cwd):
    try: return subprocess.check_output(cmd, cwd=cwd, stderr=subprocess.DEVNULL, text=True).strip()
    except Exception: return ""
def git_head(path): return run(["git", "rev-parse", "--short=12", "HEAD"], path) or "nogit"
def git_dirty(path): return bool(run(["git", "status", "--porcelain", "--untracked-files=all"], path))
def iter_files(path):
    for p in sorted(path.rglob("*")):
        if not p.is_file(): continue
        rel = p.relative_to(path)
        if any(part in EXCLUDED_DIRS for part in rel.parts): continue
        if p.suffix in EXCLUDED_SUFFIXES: continue
        if rel.parts[0] in {"src", "tests", "openapi", "docs"}: yield p; continue
        if len(rel.parts) == 1 and rel.name in INCLUDED_ROOT_FILES: yield p
def digest_service(path):
    h = hashlib.sha256()
    for f in iter_files(path):
        rel = f.relative_to(path).as_posix(); h.update(rel.encode()); h.update(b"\0"); h.update(f.read_bytes()); h.update(b"\0")
    return h.hexdigest()
def main():
    parser = argparse.ArgumentParser(); parser.add_argument("--write", action="store_true"); args=parser.parse_args()
    build_dir = ROOT / ".goftaroo-build"; build_dir.mkdir(exist_ok=True)
    build_time = dt.datetime.now(dt.UTC).replace(microsecond=0).isoformat()
    metadata = {"build_time": build_time, "services": []}
    env_lines = ["# Generated by scripts/goftaroo-source-fingerprint.py", "# Do not edit manually.", f"GOFTAROO_BUILD_TIME={build_time}"]
    for service in SERVICES:
        sp = ROOT / service["path"]
        if not sp.exists(): continue
        head=git_head(sp); dirty=git_dirty(sp); full=digest_service(sp); short=full[:16]; sha=f"{head}{'-dirty' if dirty else ''}"; prefix=env_prefix(service["name"])
        metadata["services"].append({"name":service["name"],"path":service["path"],"host_port":service["host_port"],"git_head":head,"dirty":dirty,"build_sha":sha,"source_digest":short,"source_digest_full":full})
        env_lines += [f"{prefix}_BUILD_SHA={sha}", f"{prefix}_BUILD_SOURCE_DIGEST={short}"]
    if args.write:
        (build_dir/"metadata.json").write_text(json.dumps(metadata,indent=2)+"\n",encoding="utf-8")
        parts=[]; base_env=ROOT/"infra-compose/.env.example"
        if base_env.exists(): parts.append(base_env.read_text(encoding="utf-8").rstrip())
        parts.append("\n".join(env_lines)); (build_dir/"compose.env").write_text("\n\n".join(parts).rstrip()+"\n",encoding="utf-8")
        (build_dir/"build.env").write_text("\n".join(env_lines).rstrip()+"\n",encoding="utf-8")
        print(f"[OK] Wrote {build_dir/'metadata.json'}"); print(f"[OK] Wrote {build_dir/'compose.env'}")
    else: print(json.dumps(metadata,indent=2))
if __name__ == "__main__": main()
